# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Model-Disagreement-Sampler
repo_url: '<Repository URL>'

nav:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- Examples:
  - Basic Usage: 'basic-usage.ipynb'
  - Additional Example: 'additional-example.ipynb'
